leak_test:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: valve
    extended:
      required: true
      default: false
      selector:
        boolean:
